seed: 19
mode: fit
checkpoint: null

model:
  num_classes: 5
  pretrained_encoder: true

data:
  batch_size: 16
  num_workers: 16
  train_fold: 1
  val_fold: 2
  test_fold: 3
  num_classes: 5

optimizer:
  lr: 8e-4
  backbone_lr_ratio: 0.1
  betas: [0.85, 0.95]
  weight_decay: 0.05

scheduler:
  eta_min: 1e-5

trainer:
  epochs: 130
  accumulate_grad_batches: 2
  gradient_clip_val: 0.1
  warmup_epochs: 0
  unfreeze_backbone_at_epoch: 25
  patience: 30
  amp: true

loss:
  np_weight: 1.0
  hv_weight: 1.0
  type_weight: 1.0

experiment_name: wavellkcell
save_dir: runs/wavellkcell
